In [1]:
import numpy as np
import torch
import datetime

In [2]:
from torchsummary import summary

In [3]:
import os
import sys

glp = os.path.abspath("../code")
if not glp in sys.path: sys.path.append( glp )
    
import StateUtilities as SU

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
SU.normalize_variable(19, 'Zone Temperature')

0.3

In [6]:
SU.variable_ranges

{'Day of Week': (0.0, 6.0),
 'Minutes of Day': (0.0, 1439.0),
 'Calendar Week': (1.0, 53.0),
 'Outdoor Air Temperature': (-20.0, 40.0),
 'Outdoor Air Humidity': (0.0, 100.0),
 'Outdoor Wind Speed': (0.0, 15.0),
 'Outdoor Wind Direction': (0.0, 360.0),
 'Outdoor Solar Radi Diffuse': (0.0, 1000.0),
 'Outdoor Solar Radi Direct': (0.0, 200.0),
 'Zone VAV Reheat Damper Position': (0.0, 1.0),
 'Zone Relative Humidity': (0.0, 100.0),
 'Zone CO2': (410.0, 5000.0),
 'Zone Temperature': (10.0, 40.0),
 'Zone Heating/Cooling-Mean Setpoint': (14.0, 30.0),
 'Zone Heating/Cooling-Delta Setpoint': (-10.0, 10.0)}

In [7]:
input_size  = 10
output_size = 2
hidden_size = (2*input_size+output_size) // 3

model_actor = torch.nn.Sequential(
    torch.nn.Linear(input_size, hidden_size),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_size, hidden_size),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_size, output_size)
)
model_target = torch.nn.Sequential(
    torch.nn.Linear(input_size, hidden_size),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_size, hidden_size),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_size, output_size)
)

In [8]:
model_actor

Sequential(
  (0): Linear(in_features=10, out_features=7, bias=True)
  (1): ReLU()
  (2): Linear(in_features=7, out_features=7, bias=True)
  (3): ReLU()
  (4): Linear(in_features=7, out_features=2, bias=True)
)

In [9]:
summary(model_actor, (input_size,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 7]              77
              ReLU-2                    [-1, 7]               0
            Linear-3                    [-1, 7]              56
              ReLU-4                    [-1, 7]               0
            Linear-5                    [-1, 2]              16
Total params: 149
Trainable params: 149
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


/home/daniel/pyenvs/mastarbvenv/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [10]:
t = torch.from_numpy(np.ones(input_size)[np.newaxis, :])

In [11]:
t+1

tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]], dtype=torch.float64)

In [12]:
x = torch.zeros((3,2))
y = torch.ones((3,4))
z = torch.ones((3,3)) * 2
z

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [13]:
torch.cat([x,y,z], dim=1)

tensor([[0., 0., 1., 1., 1., 1., 2., 2., 2.],
        [0., 0., 1., 1., 1., 1., 2., 2., 2.],
        [0., 0., 1., 1., 1., 1., 2., 2., 2.]])

In [14]:
torch.cat([z,y], dim=1).shape

torch.Size([3, 7])

In [15]:
y[1, 1] = 4
y

tensor([[1., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
y[0, :] = y[1, :]

In [17]:
torch.get_default_dtype()

torch.float32

In [18]:
y.shape

torch.Size([3, 4])

In [19]:
torch.cat([torch.zeros((1,15)), torch.zeros((1,15))]).shape

torch.Size([2, 15])

In [22]:
import RandomProcessExt

In [28]:
r = RandomProcessExt.OrnsteinUhlenbeckProcess(theta = 0.15, mu = 0.0, sigma = 0.2, size=3)si 

In [34]:
rsamp = r.sample()
rsamp

array([-0.07691389,  0.11421494, -0.33178793])

In [39]:
torch.from_numpy(rsamp[np.newaxis, :]) + torch.ones((1,3))

tensor([[0.9231, 1.1142, 0.6682]], dtype=torch.float64)

In [1]:
import pandas as pd

In [2]:
index_list_1 = [1,1,1,2,2,2]
index_list_2 = [1,2,3,1,2,3]

In [3]:
datalist = [{"entry 1": i**5, "entry 2": i+304} for i in range(6)]

In [4]:
datalist

[{'entry 1': 0, 'entry 2': 304},
 {'entry 1': 1, 'entry 2': 305},
 {'entry 1': 32, 'entry 2': 306},
 {'entry 1': 243, 'entry 2': 307},
 {'entry 1': 1024, 'entry 2': 308},
 {'entry 1': 3125, 'entry 2': 309}]

In [7]:
pd.DataFrame(datalist, index=[index_list_1, index_list_2])

entry 1  entry 2
1 1        0      304
  2        1      305
  3       32      306
2 1      243      307
  2     1024      308
  3     3125      309