In [3]:
import numpy as np
import torch
import datetime
import pickle

In [4]:
import os
import sys

glp = os.path.abspath("../code")
if not glp in sys.path: sys.path.append( glp )
    
import StateUtilities as SU

In [5]:
f = "../checkpoints/s114-verbose/20210505-1946/vbo-agents-1.pickle"
fl = open(f, "rb")
agents = pickle.load(fl)
fl.close()

In [6]:
f = "../checkpoints/s114-verbose/20210505-1946/vbo-status_output_dict-1.pickle"
fl = open(f, "rb")
vbo = pickle.load(fl)
fl.close()

In [7]:
f = "../checkpoints/s114-verbose/20210505-1946/vbo-building-1.pickle"
fl = open(f, "rb")
building_global_state_variables = pickle.load(fl)
fl.close()

In [8]:
building_global_state_variables

['Minutes of Day',
 'Day of Week',
 'Calendar Week',
 'SPACE1-1 Zone Temperature',
 'SPACE2-1 Zone Temperature',
 'SPACE3-1 Zone Temperature',
 'SPACE4-1 Zone Temperature',
 'SPACE5-1 Zone Temperature',
 'SPACE1-1 Zone VAV Reheat Damper Position',
 'SPACE2-1 Zone VAV Reheat Damper Position',
 'SPACE3-1 Zone VAV Reheat Damper Position',
 'SPACE4-1 Zone VAV Reheat Damper Position',
 'SPACE5-1 Zone VAV Reheat Damper Position',
 'SPACE1-1 Zone CO2',
 'SPACE2-1 Zone CO2',
 'SPACE3-1 Zone CO2',
 'SPACE4-1 Zone CO2',
 'SPACE5-1 Zone CO2',
 'SPACE1-1 Zone People Count',
 'SPACE2-1 Zone People Count',
 'SPACE3-1 Zone People Count',
 'SPACE4-1 Zone People Count',
 'SPACE5-1 Zone People Count',
 'SPACE1-1 Zone Relative Humidity',
 'SPACE2-1 Zone Relative Humidity',
 'SPACE3-1 Zone Relative Humidity',
 'SPACE4-1 Zone Relative Humidity',
 'SPACE5-1 Zone Relative Humidity',
 'Outdoor Air Temperature',
 'Outdoor Air Humidity',
 'Outdoor Wind Speed',
 'Outdoor Wind Direction',
 'Outdoor Solar Radi Dif

In [10]:
len(building_global_state_variables) == vbo[0]['norm_state_ten'].shape[1]

True

In [12]:
agents[0].input_parameters

['Minutes of Day', 'Day of Week', 'Outdoor Solar Radi Direct']

In [16]:
for iparam in agents[0].input_parameters:
    idx = building_global_state_variables.index(iparam)
    print(f"Input parameter name {iparam:33}, position: {idx}")

Input parameter name Minutes of Day                   , position: 0
Input parameter name Day of Week                      , position: 1
Input parameter name Outdoor Solar Radi Direct        , position: 33


In [9]:
vbo[0].keys()

dict_keys(['state', 'norm_state_ten', 'agent_action', 'agent internal input tensor'])

In [11]:
vbo[0]['norm_state_ten']

tensor([[-0.9166,  1.0000,  0.9615, -0.6659, -0.6519, -0.6635, -0.6522, -0.4816,
         -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -0.9999, -0.9999, -0.9999,
         -0.9999, -0.9999,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.8482,
         -0.8503, -0.8485, -0.8502, -0.8728, -0.8133,  0.7400, -0.8000, -0.5000,
         -1.0000, -1.0000]])

In [22]:
vbo[3]['norm_state_ten'][:,[0,1,33]]

tensor([[-0.6664,  1.0000, -1.0000]])

In [18]:
vbo[0]['agent_action']

7

In [19]:
vbo[0]['agent internal input tensor']

tensor([[-0.9166,  1.0000, -1.0000]])